{
 "title": "Harmony Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   {
    "name": "namespace",
    "query": "label_values(kube_namespace_labels, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Restarts",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=~\"$namespace\"}) by (container, namespace)\n",
     "legendFormat": "namespace"
    }
   ]
  },
  {
   "title": "Cluster Nodes (including masters)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "count(sum(kube_node_status_condition) by (node))"
    }
   ]
  },
  {
   "title": "Unhealthy Nodes",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status!=\"true\"})"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(max(container_memory_usage_bytes{namespace=~\"$namespace\"}) by (pod_name, namespace) / 1048576, \"Container\", \"$1\", \"pod_name\", \"(.*)\")\n# 1048576 is the amount of bytes in a mb"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Nodes Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "((1 - ((node_memory_MemFree_bytes + node_memory_Cached_bytes) / node_memory_MemTotal_bytes)) * 100)"
    }
   ]
  },
  {
   "title": "Non 2xx Response Codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "Request Total" }
   ],
   "targets": [
    {
     "expr": "sum(istio_requests_total{reporter=\"source\", response_code!~\"2.*\", response_code!~\"3.*\"}) by (source_workload,destination_workload,response_code)"
    }
   ]
  },
  {
   "title": "Harmony Request Duration from Source",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "s", "label": "Request Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.95, sum(rate(istio_request_duration_seconds_bucket{reporter=\"source\", response_code=\"200\"}[1h])) by (le, source_workload, destination_workload, request_protocol))"
    }
   ]
  }
 ]
}