{
 "title": "Kubernetes / Compute Resources / Cluster",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(node_cpu_seconds_total, cluster)"
   },
   { "name": "datacenter", "label": "datacenter", "query": "IAD*" },
   {
    "name": "environment",
    "query": "label_values(cadvisor_version_info, env)"
   },
   {
    "name": "job",
    "query": "label_values(cadvisor_version_info, job)"
   },
   {
    "name": "node",
    "query": "label_values(cadvisor_version_info{env=~\"$environment\",job=~\"$job\"}, instance)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_namespace_labels, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests by Namespace",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{name!=\"\",instance=~\"$node\",namespace=~\"$namespace\"} by (name, namespace)"
    }
   ]
  },
  { "title": "Headlines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", cluster=\"$cluster\"}[1m]))"
    }
   ]
  },
  {
   "title": "CPU Requests Commitment",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 8 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\"}) / sum(node:node_num_cpu:sum{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "CPU Limits Commitment",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 8 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\"}) / sum(node:node_num_cpu:sum{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 8 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemFreeCachedBuffers_bytes:sum{cluster=\"$cluster\"}) / sum(:node_memory_MemTotal_bytes:sum{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Memory Requests Commitment",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 8 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{cluster=\"$cluster\"}) / sum(:node_memory_MemTotal_bytes:sum{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Memory Limits Commitment",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\"}) / sum(:node_memory_MemTotal_bytes:sum{cluster=\"$cluster\"})"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "CPU Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(mixin_pod_workload{cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "count(avg(mixin_pod_workload{cluster=\"$cluster\"}) by (workload, namespace)) by (namespace)"
    },
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\"}) by (namespace) / sum(kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\"}) by (namespace) / sum(kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\"}) by (namespace)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{cluster=\"$cluster\", container_name!=\"\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Memory Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } }
 ]
}